spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scmessage
    username: scmessage
    password: scmessage
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      password: 12345678
      name: user
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: "Secure jwt auth"
server:
  port: 8081

app:
  jwt:
    # HS512 algorithm
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 2
  cors:
    allowed-origins: http://localhost:3001

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
